name: TestPioneer Dev Python 3.11

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  schedule:
    - cron: "0 1 * * *"

permissions:
  contents: read

jobs:
  build_dev_version:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r dev_requirements.txt
      - name: Test execute yaml
        run: python ./test/unit_test/test.py
      - name: Save Test video
        uses: actions/upload-artifact@v4
        with:
          name: test_video
          path: ./test/unit_test/test_video.mp4