name: TestPioneer Stable Python 3.12

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 1 * * *"

permissions:
  contents: read

jobs:
  build_dev_version:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r dev_requirements.txt
      - name: Test run yaml that execute multi scrip
        run: python ./test/unit_test/run_multi_time/test_run_multi_time.py
      - name: Test yaml that script in folder
        run: python ./test/unit_test/run_folder/test_run_folder.py
      - name: Test yaml that download file yaml
        run: python ./test/unit_test/download_file/test_run_download_file.py
      - name: Test parallel run
        run: python ./test/unit_test/parallel_run/test_parallel_run.py
      - name: Save Test video
        uses: actions/upload-artifact@v4
        with:
          name: test_video
          path: test_video.mp4
      - name: Save log file
        uses: actions/upload-artifact@v4
        with:
          name: test_log
          path: test_pioneer.log